updated the dam shell script to check if there are more than 4 arguments

diff --git a/dam b/dam
--- a/dam
+++ b/dam
@@ -10,6 +10,13 @@ mkdir /tmp/dam-mmn/1/OGG
 mkdir /tmp/dam-mmn/2
 mkdir /tmp/dam-mmn/2/MP3
 mkdir /tmp/dam-mmn/2/OGG
+
+if [ $# gt 4 ]
+  then
+    echo "ERROR: invalid command line" 1>&2
+    exit 1
+fi
+
 # execute java program
 java -cp out dam $1 $2 $3 $4 -fast
 exitVal=`echo $?`
